stages:
  - test
  - build
  - deploy
  
unittest-py34:
  stage: test
  script:
    - pip install tox
    - tox -e py34
  tags:
    - python3.4
   
docker-deploy:
  stage: deploy
  script:
    -docker build -t flask-demo .
    - if [$(docker ps -aq --filter name=web)] then docker rm -f web; fi
    - docker run -d --name web -p 5000:5000 flask-demo
  tags:
    - demo
  only:
    - master
